server:
  servlet:
    context-path: /geekshop


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/geekbrains?useUnicode=true&characterEncoding=UTF8
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: razumserdca777@gmail.com
    password: XoyHUn8q4bMkpQUZXPbi
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true

  #  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
files:
  storepath:
    icons: "F:\\Spring\\uploads\\icons"
    images: "F:\\Spring\\uploads\\images"


#geekshop:
#  rabbitmq:
#    exchange: super-shop.exchange
#    routingkey: super.shop
#    queue:super-shop.queue

documents:
  service:
    url: "localhost:10210/documents"

supershop:
  name: Evgeny
  city: Rostov-on-Don
  phone: 89997772233
  email: evg@mail.ru